language: node_js
node_js:
  - stable
cache:
  yarn: true

script: yarn test

before_deploy: yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
