language: node_js
node_js:
  - stable
cache:
  yarn: true

before_install:
  - export PATH=$PATH:`yarn global bin`
  - yarn global add travis-ci-cloudfront-invalidation
  - yarn global add greenkeeper-lockfile@1
install: yarn

before_script: greenkeeper-lockfile-update
script: yarn test
after_script: greenkeeper-lockfile-upload

before_deploy: yarn build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "blog.dustinschau.com"
  skip_cleanup: true
  local-dir: public
  acl: public_read
  on:
    branch: master
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $AWS_CLOUDFRONT_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
