[[redirects]]
  from = "/*"
  to = "https://dustinschau.com/posts/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "https://dustinschau.com/posts"
  status = 301
  force = true